[package]
name = "tp4_file_enc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "chiffreur"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
argon2 = "0.5.3"
rpassword = "7.3.1"
rand = "0.9.0"
aes-gcm = "0.10.3"
generic-array = "0.14"
